name: Comparar tokenss

on: push

jobs:
  comparar:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Comparar los tokens
        shell: powershell
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if ([string]::IsNullOrEmpty($env:DEV_TOKEN) -or
              [string]::IsNullOrEmpty($env:LOCAL_DEV_TOKEN)) {
            Write-Output "Falta uno de los tokens"
            exit 1
          }

          if ($env:DEV_TOKEN -ceq $env:LOCAL_DEV_TOKEN) {
            Write-Output "Los tokens coinciden"
            exit 0
          } else {
            Write-Output "Los tokens NO coinciden"
            exit 1
          }